#!/usr/bin/env bash

echo "deploy s3 bucket via cfn"

STACK_NAME="cfn-s3-bucket"

aws cloudformation deploy --template-file template.yaml --stack-name $STACK_NAME --no-execute-changeset --region us-east-1